### ISSUE TITLE
HowTo: Hostmetrics with pure docker 

### ISSUE THREAD

**Issue by svsk417** [SigNoz/dashboards#15]
Hi! 
I am currenty struggeling with the setup of the metrics dashboards. Therefore, I would be glad, if you provide an example on how to setup things with a docker compose file. 
What I have done so far: 
```
  hostmetrics:
    root_path: /hostfs
    scrapers:
      # CPU utilization metrics
      cpu:
      # Disk I/O metrics
      disk:
      # File System utilization metrics
      filesystem:
      # CPU load metrics
      load:
      # Memory utilization metrics
      memory:
      # Paging/Swap space utilization and I/O metrics
      paging:

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  resourcedetection:
    detectors: [ docker ]
    timeout: 2s

exporters:
  clickhousemetricswrite:
    endpoint: tcp://ENV_CLICKHOUSE_HOSTNAME:ENV_CLICKHOUSE_TCP_PORT/?database=signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true

service: 
  pipelines:
    metrics/hostsystem:
      receivers: [ hostmetrics ]
      processors: [ batch, resourcedetection ]
      exporters: [ clickhousemetricswrite ]
```
I have mounted the host file system to `/hostfs`.
I have started SigNoz and created a dashboard off the available ones in this repository, but every pane shows "No Data". Can you tell me, what I am missing? I would be willing to setup a Demo, in this repo, if you tell me. :) 
Cheers!
